version: "3.8"

services:
  encurtadordb:
    container_name: encurtadordb
    image: postgres:13
    restart: unless-stopped
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=encurtador
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-enc-volume:/var/lib/postgresql/data
    networks:
      - encurtador

  encurtador_redis:
    image: redis:5
    container_name: encurtador_redis
    ports:
      - 6373:6373
    restart: always
    networks:
      - encurtador
      
  api:
    container_name: encurtador_api
    image: encurtador-api
    build: . 
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@encurtadordb:5432/encurtador?connect_timeout=300
    depends_on:
      encurtadordb:
          condition: "service_healthy"
      
    command: bash -c "npm run migrate:deploy && npm start"
    ports:
      - "3030:3030"
    networks:
      - encurtador

networks:
  encurtador:


volumes:
  postgres-enc-volume: